name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Unity - Activate
      uses: game-ci/unity-activate@v2
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    
    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-
    
    - name: Run Tests
      uses: game-ci/unity-test-runner@v3
      with:
        artifactsPath: artifacts
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: artifacts
        retention-days: 7 