name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Unity
      uses: game-ci/setup-unity@v3
      with:
        unity-version: 2022.3.0f1
    
    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-
    
    - name: Run Tests
      uses: game-ci/unity-test-runner@v3
      with:
        artifactsPath: artifacts
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: artifacts
        retention-days: 7 